### ISSUE TITLE
2.0.1 on pypi.org does not have an accompanying tag and there is no sdist tarball

### ISSUE THREAD

**Issue by dvzrv** [NordicSemiconductor/piccata#11]
Hi! I'm packaging this project for Arch Linux. Unfortunately this project publishes version 2.0.1 on pypi.org but does not have an accompanying tag in this repository.

To mitigate supply chain attacks it is best to have an auditable trail from release (in this repository) to release artifact (on pypi.org).
Please add the tag in this repository!

**Comment by dvzrv** [comment]
As noted in the change of the title of this issue: There is no sdist tarball on pypi.org so noone can even build this project in version 2.0.1 from source. :cry: 
Please fix this and add an sdist tarball (e.g. in a patch level release).

**Comment by dvzrv** [comment]
@rlubos @wbober I'm pinging you here as you seem mainly affiliated with this project.
Without a tarball for 2.0.1 downstreams can not build this project from source, which means that python3 support is barred.

**Comment by rlubos** [comment]
Hi @dvzrv,

I've created a corresponding tag in the respository (https://github.com/NordicSemiconductor/piccata/releases/tag/2.0.1) and uploaded a 2.0.1 source distribution to PyPi (https://pypi.org/project/piccata/2.0.1/#files).

**Comment by PureTryOut** [comment]
Could the tests also be included in the sdist tarball please? We run tests when packaging software (in my case for Alpine Linux) to make sure everything works correctly with all the versions of dependencies we ship, but currently the sdist tarball doesn't include those and we still have to use the GitHub tarball using the git tag instead.

**Comment by rlubos** [comment]
@PureTryOut I did some changes to include tests in the output package. Will the following work for you?
[piccata-2.0.2.tar.gz](https://github.com/NordicSemiconductor/piccata/files/10536006/piccata-2.0.2.tar.gz)

**Comment by PureTryOut** [comment]
Yup works fine, thanks!

**Comment by rlubos** [comment]
@PureTryOut 2.0.2 has been released:
https://github.com/NordicSemiconductor/piccata/releases/tag/2.0.2
https://pypi.org/project/piccata/2.0.2/#files
