### ISSUE TITLE
2.0.2: Tests are installed into global namespace

### ISSUE THREAD

**Issue by dvzrv** [NordicSemiconductor/piccata#14]
Hi! When packaging 2.0.2 from sdist tarball for Arch Linux I noticed that all tests are installed to the global namespace (e.g. `/usr/lib/python3.10/site-packages/tests/`).

This should not be done. Please make sure that the tests are part of the sdist tarball but *not* part of the resulting wheel! :)

**Comment by rlubos** [comment]
Sorry for the fuss, I've updated the package to version 2.0.3, where tests are no longer installed.
